apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-web-yash-deploy
  labels:
    app: bank-web-yash
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bank-web-yash
  template:
    metadata:
      labels:
        app: bank-web-yash
    spec:
      containers:
        - name: bank-web
          image: us-central1-docker.pkg.dev/gcp-class-17/yash-bank-repo/bank-web-yash:v1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bank-web-yash-svc
  labels:
    app: bank-web-yash
spec:
  type: LoadBalancer
  selector:
    app: bank-web-yash
  ports:
    - name: http
      port: 80
      targetPort: 80
